PROJECT_NAME = "AI Research Assistant"

MODEL_NAME = "qwen3:4b-instruct"

SEARCH_RESULT_COUNT = 3
PAGE_MAX_CHARS = 1000

MAX_REVISIONS = 1

MODEL_TEMPERATURE = 0
MODEL_MAX_OUTPUT_TOKENS = 300

WEB_REQUEST_TIMEOUT = 10